### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dennisvang** [dennisvang/notsotuf#1]
Some detailed documentation would be nice.

**Comment by NicklasTegner** [comment]
I propose using sphinx to automatically generate api docs from the docstrings.
In addition, we can add tutorials as needed, as notsotuf matures
Then publish the sphinx docs to rtd

I would be happy to set this up, once my work on #7  has been completed

**Comment by dennisvang** [comment]
Sounds good. Thanks!
