### ISSUE TITLE
Add high-level repository tools

### ISSUE THREAD

**Issue by dennisvang** [dennisvang/notsotuf#13]
For convenience, it would be nice to have some high-level tools, e.g to handle the tasks outlined in the repo example.

**Comment by NicklasTegner** [comment]
correct me if I'm wrong. But this would be essential to complete the world in #9

**Comment by dennisvang** [comment]
> correct me if I'm wrong. But this would be essential to complete the world in #9

Yes, correct, it will be the basis for the CLI. But should be independently useful as well. Hence the separate issue.
