### ISSUE TITLE
Separate update-check method for client

### ISSUE THREAD

**Issue by dennisvang** [dennisvang/notsotuf#5]
## Description

The client currently has a single `Client.update()` method that checks for available updates and asks for confirmation via the command line before downloading and applying the update:

https://github.com/dennisvang/notsotuf/blob/1321f81b499c36c743287de3c6e1106bdb01344c/src/notsotuf/client.py#L84

This works for simple applications, but a separate update-check method would provide more flexibility.

Current:

```python
notsotuf_client = Client(...)
notsotuf_client.update(...)
```

Proposed:

```python
notsotuf_client = Client(...)
if notsotuf_client.check_for_updates(...):
    notsotuf_client.update(...)
```

**Comment by NicklasTegner** [comment]
Looking forward to this.
Feel free to tag me on relevant issues I can help with :)

**Comment by NicklasTegner** [comment]
Ohh. And in addition, it would also be nice to be able to provide a callback, for update progress monitoring, when the app being updated is a gui application

**Comment by dennisvang** [comment]
@NicklasTegner Thanks, happy to see you're interested. I would actually prefer to stick with pyupdater and improve that, but as there does not seem to be any activity there, I decided to create a minimal implementation based on `tuf` myself.

As for the progress-callback: I agree that would be nice to have, but it is `python-tuf` that does all the network handling (downloading), and, as far as I can see, they do not offer such functionality. Perhaps there is a way around that, e.g. via the underlying `requests` pacakge, but I would have to look into that some more.

In any case, my aim with `notsotuf` is to keep things as simple as possible, to minimize the maintenance burden.

**Comment by NicklasTegner** [comment]
@dennisvang  kind of answered my question already.
But just want to clarify.

Do you plan to make this into a viable solution in production (to switch from PyUpdater to this), or is this only a minimum viable product?

**Comment by dennisvang** [comment]
@NicklasTegner I am currently working to make `notsotuf` production ready, and plan to maintain it that way.

Our company's applications are going to be migrated from `pyupdater` to `notsotuf`, so that is my incentive for making sure everything works.

To minimize the amount of maintenance required, I do want to keep the number of "bells and whistles" to an absolute minimum.

So, the goal is for `notsotuf` to be production-ready, but it will *not* be a drop-in replacement for pyupdater in terms of extra functionality.

### A bit more background

Basically, we use `python-tuf` as a means to download files securely. It handles all aspects related to file manifests and file authenticity, including cryptographic signing on the repo side, as well as downloading files and verification of file authenticity on the client side. 

However, `python-tuf` only knows about a "list of files" (targets) and a way to distribute these files securely. It does not know what these files are. It assumes that a client already knows which specific file they want to download, and it stops once that file has been downloaded and verified. It does not do anything with the downloaded file. It is unaware of any "application versions".

This is where `notsotuf` steps in: notsotuf knows two specific types of file, viz. application archives and patches, and provides a layer around `python-tuf` that defines an "application version" (PEP440). It knows how to check the manifest to determine which files need to be downloaded. This is all very similar to pyupdater. 

On the client side, based on the "application version", we determine whether an update is available, and, if so, allow the user to decide if they want to download, extract, and "install" the update, again very much like pyupdater. 

The installation part is platform dependent, and, whereas pyupdater provides several built-in ways to handle this "installation" on different platforms, notsotuf only provides one way (currently only for Windows), out-of-the-box. Nevertheless, we do allow the app developer to provide their own, platform specific, callable to handle the installation part, as mentioned in issue #6.

On the repo side, notsotuf provides some tools to set up a basic TUF repository, e.g. creating keys, initializing file manifests, and updating them. We also provide some tools to create gzip archives and patches. We do not make any assumption as to what is inside the archive. Whereas PyUpdater is built around PyInstaller, notsotuf does not care what you use to build your application (could be PyInstaller, could be something else). 

Other PyUpdater functionality that is *not* supported by notsotuf (out-of-the-box):
- upload plugins to upload files to a server, for example to AWS S3
- asset updates (although these are basically supported via the underlying `python-tuf`)

**Comment by NicklasTegner** [comment]
that is all fine and all. I would suggest the following features from PyUpdater should also be ported over

* A cli interface to manage building, signing and placing files in the right place.
* As I said in another issue, MacOS support

I can do the above, when the library is more mature, if you'll like

**Comment by dennisvang** [comment]
A cli is already a work in progress, but I'm currently playing around to figure out the most convenient implementation before publishing.

Building will not be supported by notsotuf. I use PyInstaller separately, and just point notsotuf to the resulting pyinstaller bundle.

Of course, your help is much appreciated. :-)

**Comment by NicklasTegner** [comment]
Would very much like to help. What can I start working on, that you aren't alreadytoying around with on your end?

**Comment by dennisvang** [comment]
@NicklasTegner I could assign you to issue #6, if you wish?

**Comment by NicklasTegner** [comment]
yes. That sounds good :)
